### ISSUE TITLE
lang strings

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-block_percipio_home#3]
you have an empty lang string defined here:
https://github.com/skillsoftadmin/moodle-block_percipio_home/blob/develop/lang/en/block_percipio_home.php#L27

better to remove it - otherwise language translators will have trouble understanding what it's for..

also - keep in mind - Moodle uses sentence case - "Percipio Home" should probably be "Percipio home"

**Comment by skillsoftadmin** [comment]
Done.
Kindly request you to re-review.
