### ISSUE TITLE
percipio_get_launchurl_block undefined?

### ISSUE THREAD

**Issue by danmarsden** [skillsoftadmin/moodle-block_percipio_home#4]
is the percipio_get_launchurl_block function supposed to be in the mod_percipio plugin? - if so, I can't see it there in your github release either.

**Comment by danmarsden** [comment]
looks like this plugin relies on a version of mod_percipio that isn't published in your github repo or the moodle.org plugins db: 2022022124

please note - you are unable to publish a plugin that depends on another plugin version that doesn't exist in the plugins db.

**Comment by danmarsden** [comment]
also - make sure you've looked really closely at that function and make sure it doesn't allow an open redirect vulnerability:
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

**Comment by skillsoftadmin** [comment]
Done.
Kindly request you for re-review
